name: Lighthouse CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 16

      - name: Detect changes
        id: detect
        run: |
          git fetch origin master 
          DIFF=$(git diff --name-only ${{ github.sha }} origin/master)
          echo "$DIFF"
          if echo "$DIFF" | grep '^ss_scripts/ICI/'
          then
            echo "URL1=https://www.iciparisxl.be/nl/" >> $GITHUB_OUTPUT
            echo "URL2=https://www.iciparisxl.be/nl/kenzo/flower-by-kenzo/la-recolte-parisienne-eau-de-parfum/p/BP_1316643" >> $GITHUB_OUTPUT
          fi
          if echo "$DIFF" | grep '^ss_scripts/SD/'
          then
            echo "URL3=https://www.superdrug.com/" >> $GITHUB_OUTPUT
            echo "URL4=https://www.superdrug.com/travel-size/hand-moisturisers-travel-size/kenzo-flower-by-kenzo-hand-nail-cream-20ml/p/mp-00110117" >> $GITHUB_OUTPUT
          fi

      - name: Debug URLs
        run: echo URL1=${{ steps.detect.outputs.URL1 }} && echo URL2=${{ steps.detect.outputs.URL2 }} && echo URL3=${{ steps.detect.outputs.URL3 }} && echo URL4=${{ steps.detect.outputs.URL4 }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        id: lighthouse_audit
        continue-on-error: true
        with:
          urls: |
            ${{ steps.detect.outputs.URL1 }}
            ${{ steps.detect.outputs.URL2 }}
            ${{ steps.detect.outputs.URL3 }}
            ${{ steps.detect.outputs.URL4 }}
          configPath: './.github/workflows/json_configs/lighthouseCI.json'  
          uploadArtifacts: true

      - name: Send mail
        if: ${{ always() && steps.lighthouse_audit.outcome == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: ${{ secrets.MAIL_USERNAME }}
          subject: Lighthouse audit failed
          to: yury_huminski@epam.com
          body: A Lighthouse audit failed. Please check the action logs for more details.